- name: Restart HAProxy container
  become: true
  become_user: "{{ relay_haproxy_user }}"
  ansible.builtin.systemd:
    name: haproxy-relay
    state: restarted
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ relay_haproxy_uid }}"

- name: Restart ufw
  become: true
  ansible.builtin.service:
    name: ufw
    state: restarted
