- name: Reload monit systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart monit
  become: true
  ansible.builtin.service:
    name: monit
    state: restarted

- name: Reload monit
  become: true
  ansible.builtin.service:
    name: monit
    state: reloaded
