{% if args.enable_crowdsec %}
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
  namespace: haproxy-ingress
  labels:
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/component: haproxy-bouncer
type: Opaque
stringData:
  apiKey: "{{ secrets.crowdsec_bouncer_key }}"
{% endif %}
