apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailserver-tls
  namespace: mail
  labels:
    app.kubernetes.io/name: mailserver
spec:
  secretName: mailserver-tls
  issuerRef:
    name: {{ args.certmanager_issuer | default("cluster-issuer") }}
    kind: ClusterIssuer
  dnsNames:
    - "{{ args.mail_hostname }}"
    {% for domain in secrets.mailserver_domains %}
    - "{{ domain.domain }}"
    - "imap.{{ domain.domain }}"
    - "smtp.{{ domain.domain }}"
    {% endfor %}
