- name: Create alloy system group
  become: true
  ansible.builtin.group:
    name: "{{ alloy_group }}"
    system: true
    state: present
  when: alloy_enabled | bool

- name: Create alloy system user
  become: true
  ansible.builtin.user:
    name: "{{ alloy_user }}"
    group: "{{ alloy_group }}"
    groups: systemd-journal
    append: true
    system: true
    shell: /usr/sbin/nologin
    create_home: false
  when: alloy_enabled | bool

- name: Check if Alloy is present
  ansible.builtin.stat:
    path: "{{ alloy_binary_path }}"
  register: alloy_present
  when: alloy_enabled | bool

- name: Get current Alloy version
  ansible.builtin.command: "{{ alloy_binary_path }} --version"
  when:
    - alloy_enabled | bool
    - alloy_present.stat.exists
  changed_when: false
  failed_when: false
  register: alloy_current_version

- name: Install Alloy
  ansible.builtin.import_tasks: install.yml
  when: >
    alloy_enabled | bool and (
      not alloy_present.stat.exists or alloy_version not in (alloy_current_version.stdout | default(''))
    )
  notify: Restart alloy

- name: Ensure Alloy configuration directory exists
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ alloy_config_path | dirname }}"
    owner: "{{ alloy_user }}"
    group: "{{ alloy_group }}"
    mode: "u=rwx,g=rx,o="
  when: alloy_enabled | bool

- name: Ensure Alloy data directory exists
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ alloy_data_path }}"
    owner: "{{ alloy_user }}"
    group: "{{ alloy_group }}"
    mode: "u=rwx,g=rx,o="
  when: alloy_enabled | bool

- name: Deploy Alloy environment file
  become: true
  ansible.builtin.template:
    src: env.j2
    dest: /etc/alloy/env
    owner: root
    group: root
    mode: "u=rw,g=r"
  notify: Restart alloy
  when: alloy_enabled | bool

- name: Deploy Alloy configuration
  become: true
  ansible.builtin.template:
    src: config.alloy.j2
    dest: "{{ alloy_config_path }}"
    owner: "{{ alloy_user }}"
    group: "{{ alloy_group }}"
    mode: "u=rw,g=r,o=r"
  notify: Restart alloy
  when: alloy_enabled | bool

- name: Deploy Alloy systemd unit
  become: true
  ansible.builtin.template:
    src: alloy.service.j2
    dest: /etc/systemd/system/alloy.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - Daemon-reload systemd
    - Restart alloy
  when: alloy_enabled | bool

- name: Enable and start Alloy
  become: true
  ansible.builtin.systemd:
    name: alloy
    enabled: true
    state: started
    daemon_reload: true
  when: alloy_enabled | bool
