k8s_app_deployer_name: "app-deployer"
k8s_app_deployer_namespace: "kube-system"
k8s_app_deployer_linux_user: "deployer"

k8s_app_deployer_server: "https://127.0.0.1:6443"
k8s_app_deployer_token_duration: "24h"

k8s_app_deployer_kubeconfig_path: /etc/rancher/k3s/k3s.yaml
