# Install requirements for the playbook using
# `ansible-galaxy install -r requirements.yml`

collections:
  - name: community.docker
    version: ">=5.1.0"
  - name: community.general
    version: ">=13.0.0"
  - name: ansible.posix
    version: ">=2.1.0"
  - name: community.crypto
    version: ">=2.22.0"
  - name: kubernetes.core
    version: ">=6.4.0"

roles:
  # k3s
  - name: xanmanning.k3s
    src: git+https://github.com/PyratLabs/ansible-role-k3s.git
    version: 37cca2e4874296961cc0138533cadd824f4fdb74

  # swap
  - name: geerlingguy.swap
    src: git+https://github.com/geerlingguy/ansible-role-swap.git
    version: 27d6d46f298d8f13e295acec5b65623c204bd49b

  # Logrotate
  - name: arillso.logrotate
    src: git+https://github.com/arillso/ansible.logrotate.git
    version: 1.6.1

  # Fail2ban
  - name: oefenweb.fail2ban
    src: git+https://github.com/Oefenweb/ansible-fail2ban.git
    version: 4b02c28f346fddcd32f329ac1eacc5d420b35382

  # Resolv.conf
  - name: ahuffman.resolv
    src: git+https://github.com/ahuffman/ansible-resolv.git
    version: bf111291a0e0145bdb91b8fa00510bd826bb3c55

  # journald conf
  - name: 0x0I.journald
    src: git+https://github.com/0x0I/ansible-role-journald.git
    version: 26a0b11533326a5779951090e7cc4b59d3962fb4

  # Network interfaces
  - name: MichaelRigart.interfaces
    src: git+https://github.com/michaelrigart/ansible-role-interfaces.git
    version: dc80e628e6ee42937c209d539b00de8f4659f6e9
