- name: Remove deprecated or insecure packages | package-01 - package-09
  ansible.builtin.apt:
    name: '{{ os_security_packages_list }}'
    state: 'absent'
  when: os_security_packages_clean | bool

- name: Install security hardening packages (Lynis DEB-0880, AUTH-9262)
  ansible.builtin.apt:
    name:
      - libpam-tmpdir
    state: present
