{% if args.auth_mode == "authelia" %}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: observability
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ secrets.grafana_oidc_client_secret }}"
{% endif %}
