apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: observability
type: Opaque
stringData:
  admin-user: grafana-local-admin
  admin-password: "{{ secrets.grafana_admin_password }}"
