apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: remote-write-endpoint
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: promgraf-kube-prometheus-prometheus
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090
      nodePort: 13090
      protocol: TCP
