apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: authelia
type: Opaque
stringData:
  users_database.yml: |
    users:
      admin:
        disabled: false
        displayname: "Admin"
        email: "{{ args.admin_email }}"
        password: "{{ secrets.authelia_admin_password_hash }}"
        groups:
          - admins
