apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  namespace: observability
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: push-endpoint
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: single-binary
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      nodePort: 13100
      protocol: TCP
