apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id={{ secrets.velero_s3_key_id }}
    aws_secret_access_key={{ secrets.velero_s3_secret_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: velero-repo-credentials
  namespace: velero
type: Opaque
stringData:
  repository-password: "{{ secrets.velero_repo_password }}"
