apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |-
    version: 0.1
    log:
      level: info
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: true
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
    http:
      addr: :5000
    proxy:
      remoteurl: https://registry-1.docker.io
      ttl: 168h
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
