apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ args.storage_class }}"
  resources:
    requests:
      storage: {{ args.pvc_registry }}
