apiVersion: v1
kind: Secret
metadata:
  name: garage-config
  namespace: garage
type: Opaque
stringData:
  garage.toml: |-
    replication_factor = 1
    consistency_mode = "consistent"

    metadata_dir = "/data/meta"
    data_dir = "/data/blocks"
    db_engine = "lmdb"

    rpc_bind_addr = "[::]:3901"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.local"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.local"

    [admin]
    api_bind_addr = "[::]:3903"
    admin_token = "{{ secrets.garage_admin_token }}"
