apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ args.storage_class }}"
  resources:
    requests:
      storage: {{ args.pvc_garage }}
