galaxy_info:
  role_name: users
  author: youtous
  description: User management role
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - users
    - management

dependencies: []
