apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: "{{ namespace }}"
spec:
  hard:
    requests.cpu: "{{ quota_requests_cpu | default('2') }}"
    requests.memory: "{{ quota_requests_memory | default('2Gi') }}"
    limits.cpu: "{{ quota_limits_cpu | default('4') }}"
    limits.memory: "{{ quota_limits_memory | default('4Gi') }}"
    pods: "{{ quota_pods | default('20') }}"
